name: Deploy GKE Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, prod)"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging

      replicas_count:
        description: 'Cantidad de nodos de RabbitMQ'
        required: true
        default: 2
        type: number

env:
  # Variables 
  PROJECT_ID: ${{ vars.GCP_PROJECT }}
  REGION: us-central1-a
  CLUSTER_NAME: dev-gke-app
  TF_WORKING_DIR: terraform/gke-cluster

jobs:
  terraform:
    name: "Terraform Apply GKE"
    runs-on: ubuntu-latest


    steps:
      # Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Autenticación con Google Cloud
      - name: Set up Google Cloud Auth (Service Account Key)
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 

      # Configurar gcloud y Terraform
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      
      # Inicializar Terraform 
      - name: Terraform Init
        id: init
        run: |
           terraform init 
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Validar la sintaxis de Terraform
      - name: Terraform Validate
        id: validate
        run: |
           terraform validate 
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: DEBUG

      # Crear Plan de Ejecución
      - name: Terraform Plan
        id: plan
        run: |
            terraform plan -input=false \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="cluster_name=${{ env.CLUSTER_NAME }}" \
            -var="environment=${{ github.event.inputs.environment }}"
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: DEBUG

      # Aplicar el Plan
      - name: Terraform Apply
        run: |
            terraform apply  -auto-approve -input=false \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="cluster_name=${{ env.CLUSTER_NAME }}" \
            -var="environment=${{ github.event.inputs.environment }}"
        working-directory: ${{ env.TF_WORKING_DIR }}
